package com.fiap.hackaton.entity.paciente.exception;

public class PacienteNotFoundException extends Exception {

    public PacienteNotFoundException() {
        super("O paciente n√£o foi encontrado!");
    }
}
