package com.fiap.hackaton.entity.colaborador.exception;

public class ColaboradorNotFoundException extends Exception {

    public ColaboradorNotFoundException() {
        super("O colaborador n√£o foi encontrado!");
    }
}
